owner: M-BAXI
repo: status

sites:
  - name: Adoremont API
    url: https://adoremont.com/api/health
    expectStatus: 200
    maxResponseTime: 3000
  - name: Adoremontbacksystem API
    url: https://backapi.adoremont.com/api/v1/health
    expectStatus: 200
    maxResponseTime: 3000

checkInterval: 10

status-website:
  cname: status.adoremont.com
  name: Adoremont 服务状态页
  introTitle: "**Adoremont 服务状态页**"
  introMessage: 本页面展示 adoremont.com 各服务运行状态和响应时间。
